In [4]:
import pandas as pd
import numpy as np

# 1. File configuration

file_path = "../SmartMarkdown_Data_Dev_2024_2025.xlsx"
raw_sheet = "Historical_Weekly_Data"

In [5]:
# 2. Load authoritative raw dataset

df_raw = pd.read_excel(file_path,sheet_name=raw_sheet)

In [6]:
# 3. Create a separate working copy

df = df_raw.copy()

In [7]:
# 4. Initial dataset profile

print("Dataset Shape:", df_raw.shape)
print("Number of Rows:", df_raw.shape[0])
print("Number of Columns:", df_raw.shape[1])

print("\nUnique SKUs:", df_raw["SKU_ID"].nunique())

print("\nDate Range:")
print("Start:", df_raw["Week_Start"].min())
print("End  :", df_raw["Week_Start"].max())

print("\nUnique Weeks:", df_raw["Week_Start"].nunique())

Dataset Shape: (4200, 30)
Number of Rows: 4200
Number of Columns: 30

Unique SKUs: 40

Date Range:
Start: 2024-01-01 00:00:00
End  : 2025-12-29 00:00:00

Unique Weeks: 105

In [75]:
# First observations
display(df_raw.head())

# Last observations
display(df_raw.tail())

# Random observations
display(df_raw.sample(5, random_state=42))

,Week_Start,SKU_ID,Brand,Product_Name,Category,Subcategory,MRP,Unit_Cost,Selling_Price,Discount_Pct,...,Promotion_Type,Retail_Event,Festival_Flag,Season_Tag,Competitor_Price,Views,Cart_Adds,Revenue,Gross_Profit,Margin_Pct
0,2024-01-01,SKU001,H&M,Men Cotton T-Shirt,Apparel,Men T-Shirts,799,340,719.10,10,...,Regular Price,NaN,0,All Season,639.20,1243,99,40988.7,21608.7,52.72
1,2024-01-08,SKU001,H&M,Men Cotton T-Shirt,Apparel,Men T-Shirts,799,340,799.00,0,...,Regular Price,NaN,0,All Season,799.00,1325,208,44744.0,25704.0,57.45
2,2024-01-15,SKU001,H&M,Men Cotton T-Shirt,Apparel,Men T-Shirts,799,340,719.10,10,...,Regular Price,NaN,0,All Season,719.10,994,144,43865.1,23125.1,52.72
3,2024-01-22,SKU001,H&M,Men Cotton T-Shirt,Apparel,Men T-Shirts,799,340,639.20,20,...,Promotional Markdown,Republic Day Sale,0,All Season,639.20,1309,122,47300.8,22140.8,46.81
4,2024-01-29,SKU001,H&M,Men Cotton T-Shirt,Apparel,Men T-Shirts,799,340,679.15,15,...,Regular Price,NaN,0,All Season,679.15,1291,187,44823.9,22383.9,49.94

,Week_Start,SKU_ID,Brand,Product_Name,Category,Subcategory,MRP,Unit_Cost,Selling_Price,Discount_Pct,...,Promotion_Type,Retail_Event,Festival_Flag,Season_Tag,Competitor_Price,Views,Cart_Adds,Revenue,Gross_Profit,Margin_Pct
4195,2025-12-01,SKU040,Sony,Wireless Over-Ear Headphones,Electronics,Audio,5990,3830,5091.5,15,...,Promotional Markdown,Black Friday,0,All Season,5391.0,534,79,132379.0,32799.0,24.78
4196,2025-12-08,SKU040,Sony,Wireless Over-Ear Headphones,Electronics,Audio,5990,3830,5391.0,10,...,Regular Price,NaN,0,All Season,5990.0,358,49,102429.0,29659.0,28.96
4197,2025-12-15,SKU040,Sony,Wireless Over-Ear Headphones,Electronics,Audio,5990,3830,5690.5,5,...,Regular Price,NaN,0,All Season,5990.0,347,31,96738.5,31628.5,32.69
4198,2025-12-22,SKU040,Sony,Wireless Over-Ear Headphones,Electronics,Audio,5990,3830,5091.5,15,...,Festival Offer,Christmas,1,All Season,4492.5,403,34,0.0,0.0,24.78
4199,2025-12-29,SKU040,Sony,Wireless Over-Ear Headphones,Electronics,Audio,5990,3830,5091.5,15,...,Clearance,Year End Sale,0,All Season,5391.0,503,43,0.0,0.0,24.78

,Week_Start,SKU_ID,Brand,Product_Name,Category,Subcategory,MRP,Unit_Cost,Selling_Price,Discount_Pct,...,Promotion_Type,Retail_Event,Festival_Flag,Season_Tag,Competitor_Price,Views,Cart_Adds,Revenue,Gross_Profit,Margin_Pct
1743,2025-03-17,SKU017,Nike,Men Running Shoes,Footwear,Running Shoes,4995,2650,3496.50,30,...,Regular Price,NaN,0,All Season,3996.00,669,65,143356.50,34706.50,24.21
2196,2025-11-03,SKU021,Puma,Unisex Casual Sneakers,Footwear,Sneakers,3999,2000,3799.05,5,...,Regular Price,NaN,0,All Season,3399.15,389,43,129167.70,61167.70,47.36
1728,2024-12-02,SKU017,Nike,Men Running Shoes,Footwear,Running Shoes,4995,2650,4245.75,15,...,Regular Price,NaN,0,All Season,4745.25,781,112,148601.25,55851.25,37.58
3337,2025-07-28,SKU032,Wildcraft,Rain Jacket,Apparel,Rainwear,2499,1200,1624.35,35,...,Regular Price,NaN,0,Monsoon,1624.35,684,84,76344.45,19944.45,26.12
298,2025-09-08,SKU003,H&M,Men Slim Fit Chinos,Apparel,Men Trousers,1999,940,1399.30,30,...,Regular Price,NaN,0,All Season,1599.20,1176,118,69965.00,22965.00,32.82

In [76]:
df_raw.info()

<class 'pandas.DataFrame'>
RangeIndex: 4200 entries, 0 to 4199
Data columns (total 30 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Week_Start           4200 non-null   datetime64[us]
 1   SKU_ID               4200 non-null   str
 2   Brand                4200 non-null   str
 3   Product_Name         4200 non-null   str
 4   Category             4200 non-null   str
 5   Subcategory          4200 non-null   str
 6   MRP                  4200 non-null   int64
 7   Unit_Cost            4200 non-null   int64
 8   Selling_Price        4200 non-null   float64
 9   Discount_Pct         4200 non-null   int64
 10  Opening_Inventory    4200 non-null   int64
 11  Replenishment_Qty    4200 non-null   int64
 12  Available_Inventory  4200 non-null   int64
 13  Latent_Demand        4200 non-null   int64
 14  Units_Sold           4200 non-null   int64
 15  Returns_Qty          4200 non-null   int64
 16  Closing_Inventory    4200 non-null   int64
 17  Stockout_Flag        4200 non-null   int64
 18  Days_In_Inventory    4200 non-null   int64
 19  Promotion_Flag       4200 non-null   int64
 20  Promotion_Type       4200 non-null   str
 21  Retail_Event         720 non-null    str
 22  Festival_Flag        4200 non-null   int64
 23  Season_Tag           4200 non-null   str
 24  Competitor_Price     4200 non-null   float64
 25  Views                4200 non-null   int64
 26  Cart_Adds            4200 non-null   int64
 27  Revenue              4200 non-null   float64
 28  Gross_Profit         4200 non-null   float64
 29  Margin_Pct           4200 non-null   float64
dtypes: datetime64[us](1), float64(5), int64(16), str(8)
memory usage: 984.5 KB

In [77]:
# Data types
df_raw.dtypes

Week_Start             datetime64[us]
SKU_ID                            str
Brand                             str
Product_Name                      str
Category                          str
Subcategory                       str
MRP                             int64
Unit_Cost                       int64
Selling_Price                 float64
Discount_Pct                    int64
Opening_Inventory               int64
Replenishment_Qty               int64
Available_Inventory             int64
Latent_Demand                   int64
Units_Sold                      int64
Returns_Qty                     int64
Closing_Inventory               int64
Stockout_Flag                   int64
Days_In_Inventory               int64
Promotion_Flag                  int64
Promotion_Type                    str
Retail_Event                      str
Festival_Flag                   int64
Season_Tag                        str
Competitor_Price              float64
Views                           int64
Cart_Adds                       int64
Revenue                       float64
Gross_Profit                  float64
Margin_Pct                    float64
dtype: object

In [78]:
# Column names
df_raw.columns.tolist()

['Week_Start',
 'SKU_ID',
 'Brand',
 'Product_Name',
 'Category',
 'Subcategory',
 'MRP',
 'Unit_Cost',
 'Selling_Price',
 'Discount_Pct',
 'Opening_Inventory',
 'Replenishment_Qty',
 'Available_Inventory',
 'Latent_Demand',
 'Units_Sold',
 'Returns_Qty',
 'Closing_Inventory',
 'Stockout_Flag',
 'Days_In_Inventory',
 'Promotion_Flag',
 'Promotion_Type',
 'Retail_Event',
 'Festival_Flag',
 'Season_Tag',
 'Competitor_Price',
 'Views',
 'Cart_Adds',
 'Revenue',
 'Gross_Profit',
 'Margin_Pct']

In [79]:
# Check expected business key:
# One SKU should have only one record per week

duplicate_key_count = df_raw.duplicated(subset=["SKU_ID", "Week_Start"]).sum()

print("Duplicate SKU_ID + Week_Start combinations:",duplicate_key_count)

Duplicate SKU_ID + Week_Start combinations: 0

In [80]:
weeks_per_sku = (
    df_raw.groupby("SKU_ID")["Week_Start"].nunique().sort_values()
)

print(weeks_per_sku)

print("\nMinimum weeks per SKU:", weeks_per_sku.min())
print("Maximum weeks per SKU:", weeks_per_sku.max())

SKU_ID
SKU001    105
SKU002    105
SKU003    105
SKU004    105
SKU005    105
SKU006    105
SKU007    105
SKU008    105
SKU009    105
SKU010    105
SKU011    105
SKU012    105
SKU013    105
SKU014    105
SKU015    105
SKU016    105
SKU017    105
SKU018    105
SKU019    105
SKU020    105
SKU021    105
SKU022    105
SKU023    105
SKU024    105
SKU025    105
SKU026    105
SKU027    105
SKU028    105
SKU029    105
SKU030    105
SKU031    105
SKU032    105
SKU033    105
SKU034    105
SKU035    105
SKU036    105
SKU037    105
SKU038    105
SKU039    105
SKU040    105
Name: Week_Start, dtype: int64

Minimum weeks per SKU: 105
Maximum weeks per SKU: 105

In [81]:
# Missing value audit

missing_summary = pd.DataFrame({
    "Missing_Count": df_raw.isnull().sum(),
    "Missing_Percentage": (df_raw.isnull().mean() * 100).round(2)
})

missing_summary = missing_summary.sort_values(
    "Missing_Count",
    ascending=False
)

display(missing_summary)

                     Missing_Count  Missing_Percentage
Retail_Event                  3480               82.86
Week_Start                       0                0.00
Brand                            0                0.00
Product_Name                     0                0.00
Category                         0                0.00
SKU_ID                           0                0.00
MRP                              0                0.00
Unit_Cost                        0                0.00
Selling_Price                    0                0.00
Discount_Pct                     0                0.00
Opening_Inventory                0                0.00
Replenishment_Qty                0                0.00
Available_Inventory              0                0.00
Subcategory                      0                0.00
Latent_Demand                    0                0.00
Units_Sold                       0                0.00
Closing_Inventory                0                0.00
Returns_Qty                      0                0.00
Stockout_Flag                    0                0.00
Days_In_Inventory                0                0.00
Promotion_Flag                   0                0.00
Promotion_Type                   0                0.00
Festival_Flag                    0                0.00
Season_Tag                       0                0.00
Competitor_Price                 0                0.00
Views                            0                0.00
Cart_Adds                        0                0.00
Revenue                          0                0.00
Gross_Profit                     0                0.00
Margin_Pct                       0                0.00

In [82]:
# Exact duplicate rows
exact_duplicates = df_raw.duplicated().sum()

print("Exact duplicate rows:", exact_duplicates)

Exact duplicate rows: 0

In [83]:
# Inspect Retail_Event including missing values

df_raw["Retail_Event"].value_counts(dropna=False)

Retail_Event
NaN                      3480
Republic Day Sale          80
Holi                       80
Independence Day Sale      80
Navratri                   80
Dussehra                   80
Diwali                     80
Black Friday               80
Christmas                  80
Year End Sale              80
Name: count, dtype: int64

In [84]:
# Percentage distribution

(
    df_raw["Retail_Event"]
    .value_counts(dropna=False, normalize=True)
    .mul(100)
    .round(2)
)

Retail_Event
NaN                      82.86
Republic Day Sale         1.90
Holi                      1.90
Independence Day Sale     1.90
Navratri                  1.90
Dussehra                  1.90
Diwali                    1.90
Black Friday              1.90
Christmas                 1.90
Year End Sale             1.90
Name: proportion, dtype: float64

In [85]:
pd.crosstab(
    df_raw["Retail_Event"],
    df_raw["Festival_Flag"],
    dropna=False
)

Festival_Flag             0   1
Retail_Event
Black Friday             80   0
Christmas                 0  80
Diwali                    0  80
Dussehra                  0  80
Holi                      0  80
Independence Day Sale    80   0
Navratri                  0  80
Republic Day Sale        80   0
Year End Sale            80   0
NaN                    3480   0

In [86]:
df_raw[
    df_raw["Retail_Event"].notna()
][
    [
        "Week_Start",
        "SKU_ID",
        "Retail_Event",
        "Festival_Flag",
        "Promotion_Flag",
        "Season_Tag"
    ]
].head(20)

,Week_Start,SKU_ID,Retail_Event,Festival_Flag,Promotion_Flag,Season_Tag
3,2024-01-22,SKU001,Republic Day Sale,0,1,All Season
12,2024-03-25,SKU001,Holi,1,1,All Season
32,2024-08-12,SKU001,Independence Day Sale,0,1,All Season
39,2024-09-30,SKU001,Navratri,1,1,All Season
40,2024-10-07,SKU001,Dussehra,1,1,All Season
43,2024-10-28,SKU001,Diwali,1,1,All Season
47,2024-11-25,SKU001,Black Friday,0,1,All Season
51,2024-12-23,SKU001,Christmas,1,1,All Season
52,2024-12-30,SKU001,Year End Sale,0,1,All Season
56,2025-01-27,SKU001,Republic Day Sale,0,1,All Season
62,2025-03-10,SKU001,Holi,1,1,All Season
84,2025-08-11,SKU001,Independence Day Sale,0,1,All Season
90,2025-09-22,SKU001,Navratri,1,1,All Season
92,2025-10-06,SKU001,Dussehra,1,1,All Season
95,2025-10-27,SKU001,Diwali,1,1,All Season
100,2025-12-01,SKU001,Black Friday,0,1,All Season
103,2025-12-22,SKU001,Christmas,1,1,All Season
104,2025-12-29,SKU001,Year End Sale,0,1,All Season
108,2024-01-22,SKU002,Republic Day Sale,0,1,Summer
117,2024-03-25,SKU002,Holi,1,1,Summer

In [87]:
categorical_cols = [
    "SKU_ID",
    "Brand",
    "Product_Name",
    "Category",
    "Subcategory",
    "Promotion_Type",
    "Retail_Event",
    "Season_Tag"
]

cardinality = pd.DataFrame({
    "Column": categorical_cols,
    "Unique_Values": [
        df_raw[col].nunique()
        for col in categorical_cols
    ]
})

display(cardinality)

           Column  Unique_Values
0          SKU_ID             40
1           Brand             18
2    Product_Name             40
3        Category              9
4     Subcategory             36
5  Promotion_Type              4
6    Retail_Event              9
7      Season_Tag              8

In [88]:
sorted(df_raw["Retail_Event"].dropna().unique())

['Black Friday',
 'Christmas',
 'Diwali',
 'Dussehra',
 'Holi',
 'Independence Day Sale',
 'Navratri',
 'Republic Day Sale',
 'Year End Sale']

------------------------------------------------------------------------

#### Feature Availability and Leakage Audit

##### Purpose:
This step documents how selected dataset variables should be treated before
building the demand prediction model.

For each important feature, we check:
1. Whether the variable would realistically be available at prediction time.
2. Whether it should be used directly, only historically/lagged, or avoided.
3. Whether using it could introduce data leakage.
4. Whether the variable has any special limitation, such as Latent_Demand
   being available only because the dataset is synthetic.

##### Prediction setup:
We assume information available up to Week t will be used to predict demand
for Week t+1.

This audit helps ensure that future information is not accidentally used
during model training.

In [89]:
feature_audit = pd.DataFrame({
    "Column": [
        "Units_Sold",
        "Closing_Inventory",
        "Views",
        "Cart_Adds",
        "Revenue",
        "Gross_Profit",
        "Promotion_Flag",
        "Retail_Event",
        "Latent_Demand"
    ],

    "Use_in_Model": [
        "Historical only",
        "Historical/current state",
        "Historical or lagged",
        "Historical or lagged",
        "Avoid as direct predictor",
        "Avoid as direct predictor",
        "Only if known in advance",
        "Yes - calendar known",
        "Special synthetic variable"
    ],

    "Risk": [
        "Low",
        "Low",
        "Medium",
        "Medium",
        "High leakage risk",
        "High leakage risk",
        "Depends on timing",
        "Low",
        "Real-world availability issue"
    ]
})

display(feature_audit)

,Column,Use_in_Model,Risk
0,Units_Sold,Historical only,Low
1,Closing_Inventory,Historical/current state,Low
2,Views,Historical or lagged,Medium
3,Cart_Adds,Historical or lagged,Medium
4,Revenue,Avoid as direct predictor,High leakage risk
5,Gross_Profit,Avoid as direct predictor,High leakage risk
6,Promotion_Flag,Only if known in advance,Depends on timing
7,Retail_Event,Yes - calendar known,Low
8,Latent_Demand,Special synthetic variable,Real-world availability issue

In [90]:
# Selling price should not exceed MRP

price_above_mrp = df_raw[df_raw["Selling_Price"] > df_raw["MRP"]]

print("Selling_Price > MRP:", len(price_above_mrp))


# Selling price should normally remain above Unit Cost
price_below_cost = df_raw[df_raw["Selling_Price"] <= df_raw["Unit_Cost"]]

print("Selling_Price <= Unit_Cost:", len(price_below_cost))

Selling_Price > MRP: 0
Selling_Price <= Unit_Cost: 0

In [91]:
# Discount validation

expected_discount_pct = (
    (df_raw["MRP"] - df_raw["Selling_Price"])
    / df_raw["MRP"]
    * 100
)

discount_difference = (
    expected_discount_pct - df_raw["Discount_Pct"]
).abs()

print(
    "Discount_Pct mismatches:",
    (discount_difference > 0.01).sum()
)

print("Minimum Discount_Pct:", df_raw["Discount_Pct"].min())
print("Maximum Discount_Pct:", df_raw["Discount_Pct"].max())
print("Maximum discount calculation difference:", discount_difference.max())

Discount_Pct mismatches: 0
Minimum Discount_Pct: 0
Maximum Discount_Pct: 40
Maximum discount calculation difference: 7.993605777301127e-15

##### Available Inventory = Opening Inventory + Replenishment Quantity

In [92]:
# ---------------------------------------------------------
# 3. Inventory reconciliation
# ---------------------------------------------------------

expected_available_inventory = (
    df_raw["Opening_Inventory"]
    + df_raw["Replenishment_Qty"]
)

print(
    "Available_Inventory mismatches:",
    (
        df_raw["Available_Inventory"]
        != expected_available_inventory
    ).sum()
)


expected_closing_inventory = (
    df_raw["Available_Inventory"]
    - df_raw["Units_Sold"]
    + df_raw["Returns_Qty"]
)

print(
    "Closing_Inventory mismatches:",
    (
        df_raw["Closing_Inventory"]
        != expected_closing_inventory
    ).sum()
)

Available_Inventory mismatches: 0
Closing_Inventory mismatches: 0

##### Sales cannot exceed available stock

In [93]:
# Sales vs available inventory

print(
    "Units_Sold > Available_Inventory:",
    (
        df_raw["Units_Sold"]
        > df_raw["Available_Inventory"]
    ).sum()
)

Units_Sold > Available_Inventory: 0

##### Checking for negative or impossible values

In [94]:
non_negative_columns = [
    "MRP",
    "Unit_Cost",
    "Selling_Price",
    "Opening_Inventory",
    "Replenishment_Qty",
    "Available_Inventory",
    "Latent_Demand",
    "Units_Sold",
    "Returns_Qty",
    "Closing_Inventory",
    "Days_In_Inventory",
    "Competitor_Price",
    "Views",
    "Cart_Adds",
    "Revenue",
    "Gross_Profit"
]

negative_check = pd.DataFrame({
    "Column": non_negative_columns,
    "Negative_Count": [
        (df_raw[col] < 0).sum()
        for col in non_negative_columns
    ]
})

display(negative_check)

                 Column  Negative_Count
0                   MRP               0
1             Unit_Cost               0
2         Selling_Price               0
3     Opening_Inventory               0
4     Replenishment_Qty               0
5   Available_Inventory               0
6         Latent_Demand               0
7            Units_Sold               0
8           Returns_Qty               0
9     Closing_Inventory               0
10    Days_In_Inventory               0
11     Competitor_Price               0
12                Views               0
13            Cart_Adds               0
14              Revenue               0
15         Gross_Profit               0

##### Revenue Validation

Revenue = Selling_Price × Units_Sold

In [95]:
# Revenue validation

expected_revenue = (
    df_raw["Selling_Price"]
    * df_raw["Units_Sold"]
)

revenue_difference = (
    expected_revenue - df_raw["Revenue"]
).abs()

print(
    "Revenue mismatches:",
    (revenue_difference > 0.01).sum()
)

print(
    "Maximum Revenue difference:",
    revenue_difference.max()
)

Revenue mismatches: 0
Maximum Revenue difference: 2.9103830456733704e-11

##### Gross Profit Validation

Gross Profit = (Selling Price - Unit Cost) × Units Sold

In [96]:
expected_gross_profit = ((df_raw["Selling_Price"] - df_raw["Unit_Cost"])* df_raw["Units_Sold"])

gross_profit_difference = (expected_gross_profit - df_raw["Gross_Profit"]).abs()

print("Gross Profit mismatches:",(gross_profit_difference > 0.01).sum())

print("Maximum Gross Profit difference:",gross_profit_difference.max())

Gross Profit mismatches: 0
Maximum Gross Profit difference: 2.1827872842550278e-11

##### Marging Percentage Validation

Margin % = (Selling Price - Unit Cost) / Selling Price × 100

In [97]:
expected_margin_pct = (
    (df_raw["Selling_Price"] - df_raw["Unit_Cost"])
    / df_raw["Selling_Price"]
    * 100
)

margin_difference = (
    expected_margin_pct
    - df_raw["Margin_Pct"]
).abs()

print(
    "Margin_Pct mismatches:",
    (margin_difference > 0.01).sum()
)

print(
    "Maximum Margin difference:",
    margin_difference.max()
)

Margin_Pct mismatches: 0
Maximum Margin difference: 0.00498749374687435

In [98]:
# Stockout and latent-demand consistency

# Case 1:
# Latent demand exceeds available inventory.
# These rows should normally be marked as stockouts.

demand_exceeds_inventory = (
    df_raw["Latent_Demand"]
    > df_raw["Available_Inventory"]
)

print(
    "Rows where Latent_Demand > Available_Inventory:",
    demand_exceeds_inventory.sum()
)

Rows where Latent_Demand > Available_Inventory: 112

In [99]:
# Of the above rows, check whether Stockout_Flag = 1

stockout_flag_mismatch_1 = df_raw[
    (df_raw["Latent_Demand"] > df_raw["Available_Inventory"])
    &
    (df_raw["Stockout_Flag"] != 1)
]

print(
    "Demand > Inventory but Stockout_Flag != 1:",
    len(stockout_flag_mismatch_1)
)

Demand > Inventory but Stockout_Flag != 1: 0

In [100]:
# If Stockout_Flag = 1, latent demand should generally
# exceed available inventory.

stockout_flag_mismatch_2 = df_raw[
    (df_raw["Stockout_Flag"] == 1)
    &
    (df_raw["Latent_Demand"] <= df_raw["Available_Inventory"])
]

print(
    "Stockout_Flag = 1 but Demand <= Inventory:",
    len(stockout_flag_mismatch_2)
)

Stockout_Flag = 1 but Demand <= Inventory: 0

In [101]:
stockout_sales_mismatch = df_raw[
    (df_raw["Latent_Demand"] > df_raw["Available_Inventory"])
    &
    (df_raw["Units_Sold"] != df_raw["Available_Inventory"])
]

print(
    "Stockout rows where Units_Sold != Available_Inventory:",
    len(stockout_sales_mismatch)
)

Stockout rows where Units_Sold != Available_Inventory: 0

In [102]:
# Stockout frequency

stockout_summary = df_raw["Stockout_Flag"].value_counts()

print(stockout_summary)

print(
    "\nStockout Rate:",
    round(df_raw["Stockout_Flag"].mean() * 100, 2),
    "%"
)

Stockout_Flag
0    4088
1     112
Name: count, dtype: int64

Stockout Rate: 2.67 %

In [103]:
# Difference between true demand and observed sales

df_check = df_raw.copy()

df_check["Unmet_Demand"] = (
    df_check["Latent_Demand"]
    - df_check["Units_Sold"]
)

print(
    "Rows with unmet demand:",
    (df_check["Unmet_Demand"] > 0).sum()
)

print(
    "Average unmet demand when positive:",
    round(
        df_check.loc[
            df_check["Unmet_Demand"] > 0,
            "Unmet_Demand"
        ].mean(),
        2
    )
)

print(
    "Maximum unmet demand:",
    df_check["Unmet_Demand"].max()
)

Rows with unmet demand: 112
Average unmet demand when positive: 31.62
Maximum unmet demand: 92

## Stage 1 - Validation Summary

- Dataset contains 40 SKUs with 105 continuous weekly observations per SKU.
- Total observations: 4,200.
- Date range: 01-Jan-2024 to 29-Dec-2025.
- No duplicate SKU-week records or exact duplicate rows were found.
- Retail_Event nulls represent non-event weeks and are therefore structurally valid.
- Pricing, discount, inventory, revenue, gross profit and margin relationships were validated successfully.
- No invalid negative values were found in the checked business variables.
- 112 observations (2.67%) represent stockout periods.
- All stockout observations are internally consistent:
  Latent_Demand > Available_Inventory and Units_Sold is capped by available stock.
- Average unmet demand during stockout periods is 31.62 units, with a maximum of 92 units.
- The distinction between Units_Sold and Latent_Demand will be considered during EDA before finalizing the demand-regression target.

Conclusion:
The dataset is structurally and logically validated and is ready for exploratory data analysis.